import { expect, test } from '@playwright/test'
import { fixture, records } from './records-fixtures'

// A catalogue admin edits in the grid like a spreadsheet and opens a record
// as a card with its fields, its pictures and its history.
test('records are edited in the grid and opened as a card', async ({ page }) => {
  const { errors, calls } = await fixture(page)
  await page.goto('/admin/data-enrichment/records')
  const grid = page.getByRole('grid', { name: 'product list' })
  await expect(grid.locator('[data-cell="0-1"]')).toContainText('WX5678-100')
  await expect(grid.locator('.record-value.is-invalid')).toHaveText(/n\/a/)
  await page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/records-grid.png` : undefined, fullPage: false })

  const nameCell = grid.locator('[data-cell="0-2"]')
  await nameCell.click()
  await page.keyboard.type('Tote bag')
  await page.keyboard.press('Enter')
  await expect.poll(() => calls.find(call => call.name === 'record.patch')?.input).toEqual({ id: records[0].id, values: { name: 'Tote bag' }, source: 'grid' })
  await expect(page.getByText('Name of WX5678-100 updated')).toBeVisible()

  const colourCell = grid.locator('[data-cell="1-3"]')
  await colourCell.click()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('listbox', { name: 'Colour' })).toBeVisible()
  await page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/records-select.png` : undefined })
  await page.keyboard.press('Escape')

  await grid.getByRole('button', { name: 'Open WX5678-100' }).click()
  const card = page.getByRole('dialog')
  await expect(card.getByRole('heading', { name: 'WX5678-100' })).toBeVisible()
  await expect(page).toHaveURL(/record=00000000-0000-4000-8000-000000000001/)
  await expect(card.getByRole('textbox', { name: 'Name' })).toHaveValue('Canvas tote')
  await page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/records-card.png` : undefined })
  await card.getByRole('button', { name: 'Edit the field Colour' }).click()
  await expect(page.getByRole('dialog', { name: 'Edit Colour' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Edit Colour' })).toHaveCount(0)
  await expect(card.getByRole('heading', { name: 'WX5678-100' })).toBeVisible()
  await card.getByRole('button', { name: 'Add a field' }).click()
  await expect(page.getByRole('dialog', { name: 'Add a field' })).toBeVisible()
  await page.keyboard.press('Escape')
  await card.getByRole('tab', { name: /Files/ }).click()
  await expect(card.getByText('WX5678-100.02.jpg')).toBeVisible()
  await expect(card.getByText('Covering the range')).toBeVisible()
  await page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/records-files.png` : undefined })
  await card.getByRole('tab', { name: 'History' }).click()
  await expect(card.getByText('Changed in the grid')).toBeVisible()
  await page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/records-history.png` : undefined })
  await page.keyboard.press('Escape')
  await expect(page).not.toHaveURL(/record=/)
  expect(errors).toEqual([])
})

test('filters, columns, bulk actions and fields are one click away', async ({ page }) => {
  const { errors, calls } = await fixture(page)
  const shot = (name: string) => page.screenshot({ path: process.env.RECORDS_SHOTS ? `${process.env.RECORDS_SHOTS}/${name}.png` : undefined })
  await page.goto('/admin/data-enrichment/records')
  await expect(page.getByRole('heading', { name: 'Products', level: 1 })).toBeVisible()

  await page.getByRole('button', { name: 'Filters' }).click()
  await page.getByRole('button', { name: 'Add filter' }).click()
  await page.getByLabel('Field of filter 1').selectOption('colour')
  await page.getByRole('dialog').getByText('Forest').click()
  await expect.poll(() => calls.filter(call => call.name === 'record.list').at(-1)?.input).toMatchObject({ filters: [{ column: 'colour', op: 'has_any', values: ['Forest'] }] })
  await shot('records-filters')
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'Columns' }).click()
  await expect(page.getByRole('checkbox', { name: 'Launch' })).toBeChecked()
  await shot('records-columns')
  await page.getByRole('checkbox', { name: 'Launch' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('grid').getByRole('button', { name: 'Launch' })).toHaveCount(0)

  await page.getByRole('checkbox', { name: 'Select WX5678-100' }).click()
  await page.getByRole('checkbox', { name: 'Select WX5678-200' }).click()
  await expect(page.getByRole('region', { name: '2 selected' })).toBeVisible()
  await shot('records-bulk')
  await page.getByRole('button', { name: 'Set a field' }).click()
  await expect(page.getByRole('dialog', { name: 'Set a field on 2 products' })).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'More actions' }).click()
  await page.getByRole('menuitem', { name: 'Add a field' }).click()
  await expect(page.getByRole('dialog', { name: 'Add a field' })).toBeVisible()
  await page.getByLabel('Type').click()
  await page.getByRole('option', { name: 'Single select' }).click()
  await expect(page.getByRole('group', { name: 'Options' })).toBeVisible()
  await shot('records-field')
  expect(errors).toEqual([])
})
