import { expect, test } from '@playwright/test'
import { responses } from './client-fixtures'

test('desktop collection preserves selection, previews, search and account controls', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/trpc/**', async route => {
    const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
    const data = name === 'assetType.list'
      ? [(responses[name] as any[])[0], { ...(responses[name] as any[])[0], id: 'video', name: 'Motion' }]
      : responses[name] ?? []
    await route.fulfill({ json: { result: { data } } })
  })
  await page.context().addCookies([{ name: 'dam_token', value: 'local-preview-fixture', domain: '127.0.0.1', path: '/' }])
  await page.goto('/collections/campaign')
  await expect(page.locator('#client-page-context')).toContainText('Autumn essentials')
  const favorites = page.getByRole('link', { name: 'Favorites', exact: true })
  const collections = page.getByRole('link', { name: 'My collections', exact: true })
  const libraryLabel = (await page.locator('aside').getByRole('link', { name: 'Autumn essentials', exact: true }).locator('.truncate').boundingBox())!
  const collectionLabel = (await collections.locator('span').last().boundingBox())!
  expect(libraryLabel.x).toBe(collectionLabel.x)
  await expect(favorites.locator('svg')).toHaveCSS('width', '16px')
  await expect(collections).toHaveCSS('cursor', 'pointer')
  expect((await favorites.boundingBox())!.height).toBe((await collections.boundingBox())!.height)
  expect((await collections.boundingBox())!.y - (await favorites.boundingBox())!.y).toBe(40)
  await expect(page.getByRole('button', { name: 'Create collection', exact: true }).locator('svg')).toHaveCSS('width', '16px')

  await expect(page.getByRole('button', { name: /Preview / })).toHaveCount(8)
  await expect(page.getByRole('button', { name: /Preview / }).first()).toHaveCSS('padding', '8px')
  await expect(page.getByRole('button', { name: 'Display preferences', exact: true }).locator('svg')).toHaveCSS('width', '20px')
  await expect(page.locator('#client-page-context ol')).toHaveCSS('gap', '8px')
  await expect(page.locator('#client-page-context ol')).toHaveCSS('flex-wrap', 'nowrap')
  const firstAssetCheckbox = page.getByRole('checkbox', { name: 'Select Campaign — Sand.jpg', exact: true })
  await firstAssetCheckbox.focus()
  await page.keyboard.press('Space')
  await expect(firstAssetCheckbox).toBeChecked()
  const localSelection = page.locator('#client-page-context .collection__selection-container')
  await expect(localSelection).toContainText('1 item selected in')
  await localSelection.hover()
  await expect(localSelection.getByRole('button', { name: 'Select All in', exact: true })).toBeVisible()
  await page.mouse.move(0, 0)
  await expect(localSelection).toContainText('1 item selected in')
  const favoriteColor = await page.getByRole('button', { name: 'Add to favorites: Campaign — Sand.jpg', exact: true }).evaluate(element => getComputedStyle(element).color)
  await expect(firstAssetCheckbox).toHaveCSS('background-color', favoriteColor)
  await expect(firstAssetCheckbox.locator('svg')).toHaveCSS('stroke-width', '3px')
  await expect(page.getByRole('checkbox').first()).toHaveAttribute('aria-checked', 'mixed')
  await expect(page.getByRole('checkbox').first().locator('[data-checkbox-indicator="mixed"]')).toBeVisible()
  await expect(page.getByRole('checkbox').first().locator('svg')).toHaveCSS('stroke-width', '3px')
  await page.screenshot({ path: '/tmp/damvia-checkbox-rendered-weight.png' })
  await page.getByRole('checkbox').first().focus()
  await page.keyboard.press('Space')
  await expect(page.getByRole('checkbox').first()).toBeChecked()
  await expect(page.locator('.dashboard-layout-topbar__selector').getByText('8 items selected', { exact: true })).toBeVisible()
  await localSelection.hover()
  await expect(localSelection.getByRole('button', { name: 'Remove Selection in', exact: true })).toBeVisible()
  await page.mouse.move(0, 0)
  await expect(localSelection).toContainText('8 items selected in')
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Select All in', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Select All in', exact: true }).click()
  await expect(page.locator('.dashboard-layout-topbar__selector').getByText('8 items selected', { exact: true })).toBeVisible()
  const selectionToolbar = page.locator('.dashboard-layout-topbar__selector')
  await expect(selectionToolbar).toHaveCSS('font-size', '14px')
  await expect(selectionToolbar.locator('svg').first()).toHaveCSS('width', '20px')
  await expect(selectionToolbar.getByRole('button', { name: 'Download selection' }).locator('svg')).toHaveCSS('width', '20px')
  await expect(page.locator('#client-page-actions')).toHaveCSS('font-size', '14px')
  expect(await page.locator('#client-page-actions').evaluate(element => getComputedStyle(element, '::before').height)).toBe('20px')
  await page.addStyleTag({ content: '.dv-theme { --dv-size-body: 16px; }' })
  await expect(selectionToolbar).toHaveCSS('font-size', '16px')
  await expect(page.getByRole('link', { name: 'Favorites', exact: true })).toHaveCSS('font-size', '16px')
  await page.addStyleTag({ content: '.dv-theme { --dv-size-body: 14px; }' })
  await page.getByRole('checkbox').first().click()
  await expect(page.getByRole('button', { name: 'Select All in', exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search files', exact: true }).click()
  const options = page.locator('[data-search-options]')
  await expect(options).toBeVisible()
  await expect(options).toHaveCSS('border-radius', '0px')
  const mode = options.getByRole('button', { name: 'Search mode', exact: true })
  await mode.click()
  await expect(mode).toHaveText('search an exact term in')
  await expect(mode).toHaveAttribute('aria-pressed', 'true')
  await mode.focus()
  await page.keyboard.press('Space')
  await expect(mode).toHaveText('search multiple references of')
  await expect(mode).toHaveAttribute('aria-pressed', 'false')
  await page.waitForTimeout(250)
  expect(await options.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await options.getByRole('button', { name: 'Asset types', exact: true }).click()
  const photography = options.getByRole('checkbox', { name: 'Photography', exact: true })
  await expect(photography).toBeVisible()
  await expect(photography).toHaveCSS('width', '16px')
  await photography.focus()
  await page.keyboard.press('Space')
  await expect(photography).toBeChecked()
  await page.keyboard.press('Space')
  await expect(photography).not.toBeChecked()
  await page.keyboard.press('Escape')
  await expect(photography).toBeHidden()
  await expect(options.getByRole('button', { name: 'Search scope', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(options).toBeHidden()
  await page.getByRole('searchbox', { name: 'Search files', exact: true }).fill('sand')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/search\?.*q=sand/)
  await expect(page.getByRole('link', { name: 'Back to Autumn essentials', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.locator('#client-page-context')).toContainText('Autumn essentials')
  await page.getByRole('button', { name: /Preview / }).first().click()
  await expect(page.getByRole('radio', { name: 'Original (HD)', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: 'PNG', exact: true }).click()
  await expect(page.getByText('Image quality', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'My account', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Display preferences', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('radio', { name: 'List', exact: true }).nth(1).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('table')).toBeVisible()
  await page.getByRole('button', { name: 'My account', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Profile', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Manage your profile and account details.')
  expect(errors).toEqual([])
})

test('neutral authentication uses shared controls and keeps account links accessible', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/trpc/**', async route => {
    const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
    await route.fulfill({ json: { result: { data: responses[name] ?? { exists: false, imageUrl: null } } } })
  })
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Log in', exact: true })).toBeDisabled()
  await page.getByLabel('Your email').fill('alex@example.test')
  await page.getByLabel('Password', { exact: true }).fill('preview-password')
  await page.getByRole('checkbox').check()
  await expect(page.getByRole('button', { name: 'Log in', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Log in', exact: true })).toHaveCSS('background-color', 'rgb(38, 38, 38)')
  await page.getByRole('link', { name: 'Reset password', exact: true }).click()
  await expect(page.getByLabel('Email', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reset password', exact: true })).toHaveCSS('background-color', 'rgb(38, 38, 38)')
  expect(errors).toEqual([])
})

for (const tree of ['menu', 'collections'] as const) {
  test(`${tree} tree shows the current collection and continuous ancestor lines`, async ({ page }) => {
    const collection = { id: 'library', name: 'Library', public: true, children: [
      { id: 'earlier', name: 'A — Earlier collection', public: true, children: [{ id: 'other', name: 'Other assets', children: [] }] },
      { id: 'campaigns', name: 'Campaigns', public: true, children: [{ id: 'campaign', name: 'Autumn essentials', public: true, children: [] }] },
    ] }
    const menu = (item: any): any => ({ id: `menu-${item.id}`, type: 'collection', hasAccess: true, collectionId: item.id, collectionName: item.name, children: item.children.map(menu) })
    await page.route('**/trpc/**', async route => {
      const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
      const data = name === 'collection.tree' ? (tree === 'collections' ? [collection] : [])
        : name === 'menuItem.list' ? (tree === 'menu' ? [menu(collection)] : [])
        : name === 'user.me' && tree === 'collections' ? { ...(responses['user.me'] as object), role: 'guest' }
        : responses[name] ?? []
      await route.fulfill({ json: { result: { data } } })
    })
    await page.context().addCookies([{ name: 'dam_token', value: 'local-preview-fixture', domain: '127.0.0.1', path: '/' }])
    await page.goto('/collections/campaign')
    const sidebar = page.locator('aside')
    const active = sidebar.getByRole('link', { name: 'Autumn essentials', exact: true })
    await expect(active).toBeVisible()
    await expect(active).toHaveAttribute('aria-current', 'page')
    await expect(active).toHaveCSS('font-weight', '700')
    const background = await active.evaluate(element => getComputedStyle(element).backgroundColor)
    expect(background).not.toBe('rgba(0, 0, 0, 0)')
    await expect(sidebar.locator('[data-tree-connector]').first()).toHaveCSS('background-color', 'rgb(212, 212, 212)')
    await expect(sidebar.locator('[data-tree-connector]')).toHaveCount(7)
    await sidebar.getByRole('button', { name: 'Expand A — Earlier collection', exact: true }).click()
    const precedingLine = sidebar.locator('[data-tree-connector].h-full').first()
    expect((await precedingLine.boundingBox())!.height).toBe(72)
    await sidebar.getByRole('button', { name: 'Collapse Campaigns', exact: true }).click()
    await expect(active).toBeHidden()
    await sidebar.getByRole('button', { name: 'Expand Campaigns', exact: true }).click()
    await expect(active).toBeVisible()
  })
}

test('collection modals share field spacing and respond to one token change', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/trpc/**', async route => {
    const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
    const data = name === 'collection.findById' ? { ...(responses[name] as object), canEdit: true, canEditLimitedToGroupIds: true, limitedToGroupIds: [], invitations: [], parent: { id: 'library', name: 'Brand library', synchronized: true } } : responses[name] ?? []
    await route.fulfill({ json: { result: { data } } })
  })
  await page.context().addCookies([{ name: 'dam_token', value: 'local-preview-fixture', domain: '127.0.0.1', path: '/' }])
  await page.goto('/collections/campaign')
  await page.getByRole('button', { name: 'Collection actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Collection settings', exact: true }).click()
  const dialog = page.getByRole('dialog')
  for (const name of ['Details', 'Visibility', 'Appearance']) await expect(dialog.getByRole('heading', { name, exact: true })).toBeVisible()
  const label = dialog.locator('label[for="collection-description"]')
  const input = dialog.getByLabel('Description', { exact: true })
  const gap = async () => { const a = (await label.boundingBox())!; const b = (await input.boundingBox())!; return b.y - a.y - a.height }
  await expect(input).toHaveCSS('height', '40px')
  await expect(label).toHaveCSS('font-size', '14px')
  expect(await gap()).toBe(8)
  await page.screenshot({ path: '/tmp/damvia-modal-standard.png' })
  await page.addStyleTag({ content: '.dv-theme { --dv-field-gap: 12px; --dv-control-height: 48px; --dv-field-label-size: 15px; }' })
  await expect(input).toHaveCSS('height', '48px')
  await expect(label).toHaveCSS('font-size', '15px')
  expect(await gap()).toBe(12)
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Collection actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Share collection', exact: true }).click()
  await expect(dialog.getByLabel('Guest email', { exact: true })).toHaveCSS('height', '48px')
  await expect(dialog.locator('label[for="email"]')).toHaveCSS('font-size', '15px')
  const expiryLabel = (await dialog.locator('label[for="expiresAt"]').boundingBox())!
  const expiryInput = (await dialog.getByLabel('Expiry date', { exact: true }).boundingBox())!
  expect(expiryInput.y - expiryLabel.y - expiryLabel.height).toBe(12)
  expect(errors).toEqual([])
})

test('search page shows the panel with counts, the toolbar and the not-found terms', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const files = (responses['collection.findById'] as any).files.map((file: any) => ({ ...file, assetTypeId: 'type-0' }))
  const search = {
    total: 8, page: 1, totalPages: 1, previousPage: null, nextPage: null, results: files,
    facets: { assetTypes: { 'type-0': 5, 'type-1': 3 }, fileTypes: { image: 8 }, extensions: { jpg: 6, png: 2 }, recordViews: {}, attributes: { colour: { Red: 5, Blue: 3 } } },
  }
  await page.route('**/trpc/**', async route => {
    const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
    const data = name === 'collection.search' ? search
      : name === 'collection.searchNotFound' ? ['zzz']
      : name === 'recordAttribute.listFacets' ? [{ id: 'colour', name: 'colour', displayName: 'Colour', values: ['Red', 'Blue', 'Green'] }]
      : name === 'assetType.list' ? ['Events', 'Products', 'Photography with a very long category name'].map((label, i) => ({ ...(responses[name] as any[])[0], id: `type-${i}`, name: label }))
      : responses[name] ?? []
    await route.fulfill({ json: { result: { data } } })
  })
  await page.context().addCookies([{ name: 'dam_token', value: 'local-preview-fixture', domain: '127.0.0.1', path: '/' }])
  await page.goto('/search?q=sand+zzz&from_collection=campaign&search_scope=current')
  const panel = page.locator('[data-search-panel]')
  await expect(panel.getByRole('link', { name: 'Back to Autumn essentials', exact: true })).toBeVisible()
  await expect(panel.getByRole('button', { name: 'sand', exact: true })).toBeVisible()
  await expect(panel.getByRole('button', { name: /^zzz/ })).toBeVisible()
  await expect(panel.getByRole('status')).toContainText('1 of 2 not found: zzz')
  await expect(page.getByText('8 results', { exact: true })).toBeVisible()
  const fileType = page.getByRole('combobox', { name: 'File type', exact: true })
  await expect(fileType).toContainText('All files')
  await fileType.click()
  await expect(page.getByRole('option', { name: 'Images 8', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: 'Videos 0', exact: true })).toBeDisabled()
  await page.getByRole('option', { name: 'Images 8', exact: true }).click()
  await expect(page).toHaveURL(/file_types=image/)
  await expect(fileType).toContainText('Images')
  // the dropdown states the file type, so it gets no chip and is cleared from the dropdown itself
  await expect(page.getByRole('button', { name: /Remove filter File type/ })).toHaveCount(0)
  await fileType.click()
  await page.getByRole('option', { name: 'All files 8', exact: true }).click()
  await expect(page).not.toHaveURL(/file_types/)
  await expect(page.getByRole('heading', { name: 'Events (8)', exact: true })).toBeVisible()
  const events = panel.getByRole('checkbox', { name: 'Events', exact: true })
  await expect(events).toHaveAccessibleDescription('5 files')
  await expect(events).toHaveCSS('width', '16px')
  await expect(events).toHaveCSS('border-radius', '0px')
  await expect(panel.getByRole('checkbox', { name: /^Photography with a very long/ })).toHaveCount(0)
  await events.click()
  await expect(page).toHaveURL(/asset_types=type-0/)
  await expect(page.getByRole('button', { name: 'Remove filter Asset type: Events', exact: true })).toBeVisible()
  // file format and size live in the toolbar, the panel keeps asset types and attributes
  await expect(panel.getByRole('checkbox', { name: 'JPG', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'File format, Any', exact: true }).click()
  const jpg = page.getByRole('checkbox', { name: 'JPG', exact: true })
  await expect(jpg).toHaveAccessibleDescription('6 files')
  await jpg.click()
  await expect(page).toHaveURL(/extensions=jpg/)
  // the dropdown states its own choice, so no chip is added for it
  await expect(page.getByRole('button', { name: /Remove filter Format/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear formats', exact: true }).click()
  await expect(page).not.toHaveURL(/extensions/)
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'File size, Any size', exact: true }).click()
  await page.getByLabel('From', { exact: true }).fill('50')
  await page.getByLabel('To', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(page).toHaveURL(/size_min=2&size_max=50|size_max=50&size_min=2/)
  await expect(page.getByRole('button', { name: 'File size, 2 to 50 MB', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Remove filter Size/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'File size, 2 to 50 MB', exact: true }).click()
  await page.getByRole('button', { name: 'Clear size', exact: true }).click()
  await expect(page).not.toHaveURL(/size_min/)

  const exact = panel.getByRole('switch', { name: 'Exact phrase', exact: true })
  await expect(exact).not.toBeChecked()
  await exact.click()
  await expect(page).toHaveURL(/exact_match=true/)
  await exact.click()
  await expect(page).not.toHaveURL(/exact_match/)
  await panel.getByRole('checkbox', { name: 'Red', exact: true }).click()
  await expect(page).toHaveURL(/attributes(\[|%5B)colour(\]|%5D)=Red/)
  await expect(panel.getByRole('checkbox', { name: 'Green', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('checkbox', { name: 'Red', exact: true })).toBeVisible()
  // the panel owns its scrolling, so the footer sits below the values instead of over them
  expect(await page.locator('aside#client-navigation').evaluate(element => element.scrollHeight > element.clientHeight + 1)).toBe(false)
  const footerBox = (await panel.getByRole('button', { name: /Clear all filters/ }).boundingBox())!
  const lastRowBox = (await panel.getByRole('checkbox').last().boundingBox())!
  expect(lastRowBox.y + lastRowBox.height).toBeLessThanOrEqual(footerBox.y)
  await panel.getByRole('button', { name: 'Clear all filters (2)', exact: true }).click()
  await expect(page).not.toHaveURL(/asset_types/)
  await expect(page).toHaveURL(/q=sand\+zzz/)
  await panel.getByRole('button', { name: 'Copy the list', exact: true }).click()
  await expect(page.getByText('1 reference copied, one per line')).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('zzz')
  await panel.getByRole('button', { name: 'Remove them', exact: true }).click()
  await expect(page).toHaveURL(/q=sand(&|$)/)
  await page.screenshot({ path: '/private/tmp/claude-501/-Users-arnaud-Documents-Github-damvia/769748be-582c-42d5-a4c4-22d86d85089a/scratchpad/search-page.png' })
  await expect(panel.getByRole('radio', { name: 'This collection only', exact: true })).toBeChecked()
  await panel.getByRole('radio', { name: 'All collections', exact: true }).click()
  await expect(page).toHaveURL(/search_scope=all/)
  expect(errors).toEqual([])
})

test('breadcrumb ellipsis stays compact, centered and transparent', async ({ page }) => {
  const parent = { id: 'marketing', name: 'Marketing Assets', parent: { id: 'brand', name: 'Brand', parent: { id: 'season', name: 'Season', parent: { id: 'root', name: 'MARKETING ASSETS', parent: null } } } }
  await page.route('**/trpc/**', async route => {
    const name = new URL(route.request().url()).pathname.split('/trpc/')[1]
    const data = name === 'collection.findById' ? { ...(responses[name] as object), name: 'EVT-25028 Festival Aurora 2025', parent } : responses[name] ?? []
    await route.fulfill({ json: { result: { data } } })
  })
  await page.context().addCookies([{ name: 'dam_token', value: 'local-preview-fixture', domain: '127.0.0.1', path: '/' }])
  await page.goto('/collections/campaign')
  const currentLabel = page.locator('#client-page-context .dv-breadcrumb__current .dv-breadcrumb__label')
  await expect(currentLabel).toHaveText('EVT-25028 Festival Aurora 2025')
  expect(await currentLabel.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  const trigger = page.getByRole('button', { name: 'Show 2 hidden path items', exact: true })
  await expect(trigger).toHaveCSS('width', '20px')
  await trigger.hover()
  await expect(trigger).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  const button = (await trigger.boundingBox())!
  const icon = (await trigger.locator('svg').boundingBox())!
  expect(Math.abs(button.x + button.width / 2 - icon.x - icon.width / 2)).toBeLessThan(0.5)
  expect(Math.abs(button.y + button.height / 2 - icon.y - icon.height / 2)).toBeLessThan(0.5)
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitem', { name: 'Season', exact: true })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: 'Brand', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})
